const ADMIN_PASSWORD = 'morley'; // Change this before publishing.
const presetKey = 'morley-presets-v1';
const links = [
  ['01', 'EndlessAudios™ — Discord Server', 'Der Treffpunkt für neue Drops, Editing-Talk und die EndlessAudios™ Community.', 'https://discord.gg/ehVMQtUacr'],
  ['02', 'Editing Presets — Morley.ae', 'Entdecke die aktuelle Morley.ae Preset-Collection und gib deinen Edits einen eigenen Look.', '/presets'],
  ['03', 'EndlessAudios™ — TikTok', 'Edits, Sounds und neue Ideen direkt aus dem EndlessAudios™ Feed.', 'https://www.tiktok.com/@endlessaudioss'],
  ['04', 'Morley.ae — TikTok', 'Kurze Preset-Demos, Workflow-Momente und frische Inspiration von Morley.ae.', 'https://www.tiktok.com/@morley.ae'],
  ['05', 'Morley.ae — Instagram', 'Behind the scenes, neue Releases und der visuelle Feed von Morley.ae.', 'https://www.instagram.com/morley.ae']
];
const starterProducts = [
  { title: 'Nightshift Pack', description: 'Dunkle Kontraste, kinoreife Blautöne und ein Mood für spätnächtliche Edits.', price: '9,99 €', image: 'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=1000&q=85', link: 'https://payhip.com' },
  { title: 'Chrome Dreams', description: 'Kühle Highlights und präzise Farben für futuristische Clips mit maximalem Impact.', price: '12,99 €', image: 'https://images.unsplash.com/photo-1519608487953-e999c86e7454?auto=format&fit=crop&w=1000&q=85', link: 'https://payhip.com' },
  { title: 'Afterglow', description: 'Warme Lichtlecks, sanfte Schatten und der letzte Glow einer goldenen Stunde.', price: '7,99 €', image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1000&q=85', link: 'https://payhip.com' }
];
const $ = (selector) => document.querySelector(selector);
const observeReveals = () => document.querySelectorAll('.reveal:not(.observed)').forEach(el => { el.classList.add('observed'); new IntersectionObserver(([entry], observer) => { if (entry.isIntersecting) { el.classList.add('visible'); observer.unobserve(el); } }, { threshold: .12 }).observe(el); });
const products = () => { try { return [...starterProducts, ...JSON.parse(localStorage.getItem(presetKey) || '[]')]; } catch { return starterProducts; } };
function renderLinks() { const list = $('#link-list'); if (!list) return; list.innerHTML = links.map(([num,title,copy,url]) => `<a class="link-row" href="${url}" ${url.startsWith('http') ? 'target="_blank" rel="noopener"' : ''}><span class="link-index">${num}</span><span class="link-main"><span class="link-title">${title}</span><small>${copy}</small></span><span class="link-arrow">↗</span></a>`).join(''); }
function renderProducts() { const grid = $('#product-grid'), template = $('#product-template'); grid.innerHTML = ''; products().forEach((product, index) => { const node = template.content.cloneNode(true); const article = node.querySelector('article'), img = node.querySelector('img'); img.src = product.image; img.alt = `${product.title} Vorschau`; node.querySelector('.product-number').textContent = `0${index + 1}`.slice(-2); node.querySelector('h3').textContent = product.title; node.querySelector('.product-price').textContent = product.price; node.querySelector('.product-description').textContent = product.description; const buy = node.querySelector('.buy-button'); buy.href = product.link || 'https://payhip.com'; grid.append(node); }); observeReveals(); }
function route() { const isPresets = location.pathname.startsWith('/presets') || location.hash.startsWith('#/presets'); $('#home-view')?.classList.toggle('is-hidden', isPresets); $('#presets-view')?.classList.toggle('is-hidden', !isPresets); document.querySelectorAll('[data-route]').forEach(a => a.classList.toggle('active', a.dataset.route === (isPresets ? 'presets' : 'home'))); window.scrollTo({ top: 0, behavior: 'smooth' }); observeReveals(); }
function setupAdmin() { const modal = $('#admin-modal'); $('#admin-trigger').addEventListener('click', () => modal.showModal()); document.querySelectorAll('[data-close-modal]').forEach(el => el.addEventListener('click', () => modal.close())); modal.addEventListener('click', e => { if (e.target === modal) modal.close(); }); $('#login-form').addEventListener('submit', e => { e.preventDefault(); const valid = $('#admin-password').value === ADMIN_PASSWORD; $('#login-error').textContent = valid ? '' : 'Dieses Passwort stimmt nicht.'; if (valid) { $('#login-panel').hidden = true; $('#admin-panel').hidden = false; } }); $('#logout').addEventListener('click', () => { $('#admin-panel').hidden = true; $('#login-panel').hidden = false; $('#admin-password').value = ''; }); $('#product-form').addEventListener('submit', e => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); const saved = JSON.parse(localStorage.getItem(presetKey) || '[]'); saved.push(data); localStorage.setItem(presetKey, JSON.stringify(saved)); e.currentTarget.reset(); $('#save-message').textContent = 'Gespeichert — dein neues Produkt ist jetzt sichtbar.'; renderProducts(); }); }
$('#year').textContent = new Date().getFullYear(); renderLinks(); renderProducts(); setupAdmin(); window.addEventListener('hashchange', route); route();
